services:
  backend:
    image: backend:latest
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: NODE-backend
    ports:
      - "4040:4040"
    env_file:
      - ./server/.env.prod
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040/health"]
      interval: 3000s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: NEXT-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:4040
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
