FROM node:22.17.1


WORKDIR /app

# Add node_modules/.bin to PATH
ENV PATH="/app/node_modules/.bin:$PATH"

# Copy package files
COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4040

CMD [ "npm", "run", "start" ]
